fix broken tarantool-cartridge helm chart
tarantool/tarantool-operator pull request #125
Opened 2022-02-11 13:33 UTC by zwirec

2022-02-11 13:36 UTC, vanyarock01 requested changes
And you forgot to add the changes to the changelog

2022-03-09 07:25 UTC, vanyarock01 requested changes

2022-03-09 07:25 UTC, vanyarock01 commented on helm-charts/tarantool-cartridge/templates/deployment.yaml
> -        fsGroup: { { .securityContext.fsGroup } }
Should add a default value (e.g 1200) to values.yaml

2022-03-10 14:47 UTC, vasiliy-t approved these changes

2022-03-10 14:47 UTC, vasiliy-t commented on helm-charts/tarantool-cartridge/templates/deployment.yaml
> +        storageClassName: "csi-ceph-ssd-dp1"
this is vkcs specific valued, I think this should not be included in chart

2022-03-10 14:51 UTC, merged