Support configurable domain cluster name
tarantool/tarantool-operator pull request #42
Opened 2020-11-25 08:24 UTC by vanyarock01

By default domain cluster name is `cluster.local`.
To change add variable `ClusterDomainName` to cartridge `values.yaml`. For example, :
```yaml
ClusterEnv: dev
ClusterName: test-app
ClusterDomainName: domain.name
...
```

Using the minicube for testing: 
```
minikube start --dns-domain='custom.domain' --extra-config='kubelet.cluster-domain=custom.domain'
```

2020-11-25 12:12 UTC, vasiliy-t requested changes

2020-11-25 12:12 UTC, vasiliy-t commented on examples/kv/helm-chart/templates/deployment.yaml
> +        tarantool.io/cluster-domain-name: "{{ default "cluster.local" $.Values.ClusterDomainName }}"
default should be defined in values.yaml

2020-11-25 12:12 UTC, vasiliy-t commented on pkg/topology/builtin.go
> +		return errors.New("cluster domain name empty")
this looks like breaking change

2020-11-26 09:35 UTC, vasiliy-t approved these changes

2020-11-26 09:48 UTC, vanyarock01 commented
@timjohncurtis Take a look, please.

2020-11-30 07:51 UTC, timjohncurtis approved these changes
yep looks good to me 👍

2020-11-30 08:09 UTC, merged